import { Roboto, Poppins  } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"], 
  weight: ["400","500","700"],
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"], 
  weight: ["400","500","700"],
  variable: "--font-roboto",
});

export const metadata = {
  title: "Smart Command",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body
        className={`${roboto.variable} ${poppins.variable} antialiased w-screen h-screen box-border`}
      >
        {children}
      </body>
    </html>
  );
}
